//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DataAccess.AutenticarService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AutenticarSoap", Namespace="http://www.sima.com.pe/")]
    public partial class Autenticar : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LogOnOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOptionsByProfileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Autenticar() {
            this.Url = global::DataAccess.Properties.Settings.Default.DataAccess_AutenticarService_Autenticar;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LogOnCompletedEventHandler LogOnCompleted;
        
        /// <remarks/>
        public event GetOptionsByProfileCompletedEventHandler GetOptionsByProfileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sima.com.pe/LogOn", RequestNamespace="http://www.sima.com.pe/", ResponseNamespace="http://www.sima.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespuestaBE LogOn(string Login, string Password, bool ValidaAD) {
            object[] results = this.Invoke("LogOn", new object[] {
                        Login,
                        Password,
                        ValidaAD});
            return ((RespuestaBE)(results[0]));
        }
        
        /// <remarks/>
        public void LogOnAsync(string Login, string Password, bool ValidaAD) {
            this.LogOnAsync(Login, Password, ValidaAD, null);
        }
        
        /// <remarks/>
        public void LogOnAsync(string Login, string Password, bool ValidaAD, object userState) {
            if ((this.LogOnOperationCompleted == null)) {
                this.LogOnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogOnOperationCompleted);
            }
            this.InvokeAsync("LogOn", new object[] {
                        Login,
                        Password,
                        ValidaAD}, this.LogOnOperationCompleted, userState);
        }
        
        private void OnLogOnOperationCompleted(object arg) {
            if ((this.LogOnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogOnCompleted(this, new LogOnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sima.com.pe/GetOptionsByProfile", RequestNamespace="http://www.sima.com.pe/", ResponseNamespace="http://www.sima.com.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetOptionsByProfile(int IdSistema, int IdUsuario) {
            object[] results = this.Invoke("GetOptionsByProfile", new object[] {
                        IdSistema,
                        IdUsuario});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetOptionsByProfileAsync(int IdSistema, int IdUsuario) {
            this.GetOptionsByProfileAsync(IdSistema, IdUsuario, null);
        }
        
        /// <remarks/>
        public void GetOptionsByProfileAsync(int IdSistema, int IdUsuario, object userState) {
            if ((this.GetOptionsByProfileOperationCompleted == null)) {
                this.GetOptionsByProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOptionsByProfileOperationCompleted);
            }
            this.InvokeAsync("GetOptionsByProfile", new object[] {
                        IdSistema,
                        IdUsuario}, this.GetOptionsByProfileOperationCompleted, userState);
        }
        
        private void OnGetOptionsByProfileOperationCompleted(object arg) {
            if ((this.GetOptionsByProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOptionsByProfileCompleted(this, new GetOptionsByProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sima.com.pe/")]
    public partial class RespuestaBE {
        
        private int idUsuarioField;
        
        private ModoExiste estadoField;
        
        private System.Data.DataTable miPerfilField;
        
        /// <comentarios/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public ModoExiste Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public System.Data.DataTable MiPerfil {
            get {
                return this.miPerfilField;
            }
            set {
                this.miPerfilField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sima.com.pe/")]
    public enum ModoExiste {
        
        /// <comentarios/>
        DAyBD,
        
        /// <comentarios/>
        NoDA,
        
        /// <comentarios/>
        NoDAyBD,
        
        /// <comentarios/>
        NoBD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void LogOnCompletedEventHandler(object sender, LogOnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogOnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogOnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaBE Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaBE)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetOptionsByProfileCompletedEventHandler(object sender, GetOptionsByProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOptionsByProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOptionsByProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591