create or replace PROCEDURE INS_APROBACIONES_PRESUPUESTO(
VAR_ID_NIVEL IN INTEGER,VAR_ID_PRESUP IN INTEGER, VAR_ORDEN IN INTEGER,
VAR_ESTADO IN INTEGER, VAR_USR_REG IN VARCHAR2, VAR_OBS IN VARCHAR2)
IS BEGIN 

INSERT INTO T_APROB_PRESUP (ID_NIVEL,ID_PRESUP,ORDEN,ESTADO,USR_REG,FEC_REG,OBS)
VALUES(VAR_ID_NIVEL,VAR_ID_PRESUP,VAR_ORDEN,VAR_ESTADO,VAR_USR_REG,SYSDATE,VAR_OBS); 

END INS_APROBACIONES_PRESUPUESTO;
