-- Generado por Oracle SQL Developer Data Modeler 4.1.5.907
--   en:        2017-04-25 00:45:58 COT
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g




CREATE TABLE T_ACCESO
  ( ACCESO INTEGER NOT NULL , "DESC" VARCHAR2 (500)
  ) ;
ALTER TABLE T_ACCESO ADD CONSTRAINT T_ACCESO_PK PRIMARY KEY ( ACCESO ) ;


-- After Create script example for table T_ACCESO
CREATE TABLE T_ACC_PERFIL
  (
    ID_PERFIL INTEGER NOT NULL ,
    ACCESO    INTEGER NOT NULL
  ) ;


-- After Create script example for table T_ACC_PERFIL
CREATE TABLE T_APROB_PRESUP
  (
    ID_APROB_PRESUP INTEGER NOT NULL ,
    ID_NIVEL        INTEGER NOT NULL ,
    ID_PRESUP       INTEGER NOT NULL ,
    ID_TP_PRESUP    INTEGER NOT NULL ,
    ID_VSN          INTEGER NOT NULL ,
    ID_DTLL         INTEGER NOT NULL ,
    ORDEN           INTEGER ,
    USR_APROB       VARCHAR2 (100) ,
    FEC_APROB       DATE ,
    ESTADO          INTEGER ,
    USR_REG         VARCHAR2 (100) ,
    FEC_REG         DATE ,
    OBS             VARCHAR2 (500)
  ) ;
COMMENT ON COLUMN T_APROB_PRESUP.ORDEN
IS
  'ORDEN DE APROBACION ' ;
  COMMENT ON COLUMN T_APROB_PRESUP.USR_APROB
IS
  'El usuario que debe aprobar el presupuesto, tipo, version o detalle' ;
ALTER TABLE T_APROB_PRESUP ADD CONSTRAINT APROBACION_PRESUP_PK PRIMARY KEY ( ID_APROB_PRESUP ) ;


-- After Create script example for table T_APROB_PRESUP
CREATE TABLE T_ARCHIVO
  (
    ID_ARCHIVO   INTEGER NOT NULL ,
    NOMB_ARCHIVO VARCHAR2 (100) ,
    TIPO_ARCHIVO VARCHAR2 (100) ,
    RUTA_ARCHIVO VARCHAR2 (250) ,
    ARCH_FEC_REG DATE ,
    ARCH_USR_REG VARCHAR2 (100)
  ) ;
ALTER TABLE T_ARCHIVO ADD CONSTRAINT T_ARCHIVO_PK PRIMARY KEY ( ID_ARCHIVO ) ;


-- After Create script example for table T_ARCHIVO
CREATE TABLE T_DET_ARCHIVO
  (
    ID_DETALLE INTEGER NOT NULL ,
    ID_ARCHIVO INTEGER NOT NULL
  ) ;


-- After Create script example for table T_DET_ARCHIVO
CREATE TABLE T_DET_VERSION
  (
    ID_DETALLE       INTEGER NOT NULL ,
    COD_MATERIAL     VARCHAR2 (100) ,
    CANT_SOLIC       NUMBER ,
    PRECIO_UNI_SOLIC NUMBER ,
    CRITICIDAD       INTEGER ,
    TOTAL_SOLIC      NUMBER ,
    TIPO             INTEGER ,
    LARGO            NUMBER ,
    ANCHO            NUMBER ,
    ALTO             NUMBER ,
    SUSTENTO         VARCHAR2 (500) ,
    UNID_SOLI        VARCHAR2 (100) ,
    DET_V_FEC_REG    DATE ,
    DET_V_ULT_FEC    DATE ,
    DET_V_USR_REG    VARCHAR2 (100) ,
    DET_V_ULT_USR    VARCHAR2 (100) ,
    ID_PRIORIDAD     INTEGER NOT NULL ,
    ID_VERSION       INTEGER NOT NULL
  ) ;
ALTER TABLE T_DET_VERSION ADD CONSTRAINT T_DETALLE_VERSION_PK PRIMARY KEY ( ID_DETALLE ) ;


-- After Create script example for table T_DET_VERSION
CREATE TABLE T_MES_ENT_SOL
  (
    ID_MES_ENTREGA  INTEGER NOT NULL ,
    ID_DETALLE      INTEGER NOT NULL ,
    MES             INTEGER ,
    TIPO            INTEGER ,
    MES_ENT_FEC_REG DATE ,
    MES_ENT_USR_REG VARCHAR2 (100)
  ) ;
ALTER TABLE T_MES_ENT_SOL ADD CONSTRAINT T_MES_ENT_SOL_PK PRIMARY KEY ( ID_MES_ENTREGA ) ;


-- After Create script example for table T_MES_ENT_SOL
CREATE TABLE T_NIVEL_APROB
  (
    ID_NIVEL       INTEGER NOT NULL ,
    N_APROB_NOMBRE VARCHAR2 (100) ,
    USR_REG        VARCHAR2 (100) ,
    FECH_REG       DATE ,
    ESTADO         INTEGER
  ) ;
COMMENT ON COLUMN T_NIVEL_APROB.ESTADO
IS
  '1: ACTIVO, 0 : INACTIVO' ;
ALTER TABLE T_NIVEL_APROB ADD CONSTRAINT T_NIVEL_APROBACION_PK PRIMARY KEY ( ID_NIVEL ) ;


-- After Create script example for table T_NIVEL_APROB
CREATE TABLE T_OBSERVACIONES
  (
    ID_OBSERVACIONES INTEGER NOT NULL ,
    ID_DET           INTEGER NOT NULL ,
    OBSERVACION      VARCHAR2 (500) ,
    OBS_USR_REG      VARCHAR2 (100) ,
    OSB_FEC_REG      DATE ,
    OBS_USR_RES      VARCHAR2 (100) ,
    OBS_FEC_RES      DATE ,
    OBS_RES          VARCHAR2 (500)
  ) ;
ALTER TABLE T_OBSERVACIONES ADD CONSTRAINT T_OBSERVACIONES_PK PRIMARY KEY ( ID_OBSERVACIONES ) ;


-- After Create script example for table T_OBSERVACIONES
CREATE TABLE T_PERFILES
  (
    ID_PERFIL INTEGER NOT NULL ,
    NOMBRE    VARCHAR2 (500) ,
    ESTADO    INTEGER
  ) ;
COMMENT ON COLUMN T_PERFILES.ESTADO
IS
  '0: INACTIVO; 1:ACTIVO' ;
ALTER TABLE T_PERFILES ADD CONSTRAINT T_PERFILES_PK PRIMARY KEY ( ID_PERFIL ) ;


-- After Create script example for table T_PERFILES
CREATE TABLE T_PERFIL_NIVEL_APROB
  (
    ID_PERFIL      INTEGER NOT NULL ,
    ID_NIVEL_APROB INTEGER NOT NULL
  ) ;


-- After Create script example for table T_PERFIL_NIVEL_APROB
CREATE TABLE T_PERFIL_USR
  (
    USUARIO   VARCHAR2 (100) ,
    ID_PERFIL INTEGER NOT NULL
  ) ;


-- After Create script example for table T_PERFIL_USR
CREATE TABLE T_PRESUP
  (
    ID_PRESUPUESTO INTEGER NOT NULL ,
    FECHA_REG      DATE ,
    USUARIO_REG    VARCHAR2 (100) ,
    ULT_MODIF_FEC  DATE ,
    ULT_MODIF_USER VARCHAR2 (100) ,
    FECHA_VAL_INI  DATE ,
    FECHA_VAL_FIN  DATE ,
    EST_ACTUAL     INTEGER ,
    NOMB_PRESUP    VARCHAR2 (150)
  ) ;
ALTER TABLE T_PRESUP ADD CONSTRAINT T_PRESUPUESTO_PK PRIMARY KEY ( ID_PRESUPUESTO ) ;


-- After Create script example for table T_PRESUP
CREATE TABLE T_PRESUP_TIPO
  (
    ID_PRESUPUESTO_TIPO INTEGER NOT NULL ,
    ID_PRESUPUESTO      INTEGER NOT NULL ,
    ID_TIPO             INTEGER NOT NULL ,
    PRE_T_FECHA_REG     DATE ,
    PRE_T_ULT_MODIF_FEC DATE ,
    PRE_T_MODIF_USR     VARCHAR2 (100) ,
    PRE_T_FECHA_VAL_INI DATE ,
    PRE_T_FECHA_VAL_FIN DATE ,
    PRE_T_EST_ACTUAL    INTEGER
  ) ;
ALTER TABLE T_PRESUP_TIPO ADD CONSTRAINT T_PRESUPUESTO_TIPO_PK PRIMARY KEY ( ID_PRESUPUESTO_TIPO ) ;


-- After Create script example for table T_PRESUP_TIPO
CREATE TABLE T_PRIORIDAD
  (
    ID_PRIORIDAD INTEGER NOT NULL ,
    NOMBRE_PRIO  VARCHAR2 (100)
  ) ;
ALTER TABLE T_PRIORIDAD ADD CONSTRAINT T_PRIORIDAD_PK PRIMARY KEY ( ID_PRIORIDAD ) ;


-- After Create script example for table T_PRIORIDAD
CREATE TABLE T_TIPO_PRESUP
  (
    ID_TIPO_PRESUP INTEGER NOT NULL ,
    NOMBRE         VARCHAR2 (100)
  ) ;
ALTER TABLE T_TIPO_PRESUP ADD CONSTRAINT T_TIPO_PRESUPUESTO_PK PRIMARY KEY ( ID_TIPO_PRESUP ) ;


-- After Create script example for table T_TIPO_PRESUP
CREATE TABLE T_VERSION
  (
    ID_VERSION          INTEGER NOT NULL ,
    NRO                 INTEGER ,
    ID_PRESUPUESTO_TIPO INTEGER NOT NULL ,
    ID_AREA             VARCHAR2 (100) ,
    V_FECHA_REG         DATE ,
    V_USUARIO_REG       VARCHAR2 (100) ,
    V_ULT_MODIF_FEC     DATE ,
    V_FECHA_VAL_INI     DATE ,
    V_FECHA_VAL_FIN     DATE ,
    EST_ACTUAL          INTEGER
  ) ;
ALTER TABLE T_VERSION ADD CONSTRAINT T_VERSION_PK PRIMARY KEY ( ID_VERSION ) ;


-- After Create script example for table T_VERSION
ALTER TABLE T_OBSERVACIONES ADD CONSTRAINT TABLE_30_T_DTL_VSN_FK FOREIGN KEY ( ID_DET ) REFERENCES T_DET_VERSION ( ID_DETALLE ) ;

ALTER TABLE T_ACC_PERFIL ADD CONSTRAINT T_ACC_PERFIL_T_ACCESO_FK FOREIGN KEY ( ACCESO ) REFERENCES T_ACCESO ( ACCESO ) ;

ALTER TABLE T_ACC_PERFIL ADD CONSTRAINT T_ACC_PERFIL_T_PERFILES_FK FOREIGN KEY ( ID_PERFIL ) REFERENCES T_PERFILES ( ID_PERFIL ) ;

ALTER TABLE T_APROB_PRESUP ADD CONSTRAINT T_APRB_PRESP_T_PRESP_TP_FK FOREIGN KEY ( ID_TP_PRESUP ) REFERENCES T_PRESUP_TIPO ( ID_PRESUPUESTO_TIPO ) ;

ALTER TABLE T_APROB_PRESUP ADD CONSTRAINT T_APRB_PRESUP_T_DTL_VSN_FK FOREIGN KEY ( ID_DTLL ) REFERENCES T_DET_VERSION ( ID_DETALLE ) ;

ALTER TABLE T_APROB_PRESUP ADD CONSTRAINT T_APRB_PRESUP_T_NVL_APRB_FK FOREIGN KEY ( ID_NIVEL ) REFERENCES T_NIVEL_APROB ( ID_NIVEL ) ;

ALTER TABLE T_APROB_PRESUP ADD CONSTRAINT T_APRB_PRESUP_T_PRESUP_FK FOREIGN KEY ( ID_PRESUP ) REFERENCES T_PRESUP ( ID_PRESUPUESTO ) ;

ALTER TABLE T_APROB_PRESUP ADD CONSTRAINT T_APRB_PRESUP_T_VSN_FK FOREIGN KEY ( ID_VSN ) REFERENCES T_VERSION ( ID_VERSION ) ;

ALTER TABLE T_DET_ARCHIVO ADD CONSTRAINT T_DET_ARV_T_ARCHIVO_FK FOREIGN KEY ( ID_ARCHIVO ) REFERENCES T_ARCHIVO ( ID_ARCHIVO ) ;

ALTER TABLE T_DET_ARCHIVO ADD CONSTRAINT T_DET_ARV_T_DET_VSN_FK FOREIGN KEY ( ID_DETALLE ) REFERENCES T_DET_VERSION ( ID_DETALLE ) ;

ALTER TABLE T_DET_VERSION ADD CONSTRAINT T_DET_VERSION_T_VERSION_FK FOREIGN KEY ( ID_VERSION ) REFERENCES T_VERSION ( ID_VERSION ) ;

ALTER TABLE T_DET_VERSION ADD CONSTRAINT T_DET_VSN_T_PRIORIDAD_FK FOREIGN KEY ( ID_PRIORIDAD ) REFERENCES T_PRIORIDAD ( ID_PRIORIDAD ) ;

ALTER TABLE T_MES_ENT_SOL ADD CONSTRAINT T_MES_ENTSOL_T_DET_VSN_FK FOREIGN KEY ( ID_DETALLE ) REFERENCES T_DET_VERSION ( ID_DETALLE ) ;

ALTER TABLE T_PERFIL_USR ADD CONSTRAINT T_PERFIL_USR_PERF_FK FOREIGN KEY ( ID_PERFIL ) REFERENCES T_PERFILES ( ID_PERFIL ) ;

ALTER TABLE T_PERFIL_NIVEL_APROB ADD CONSTRAINT T_PRF_NIVEL_APROB_T_PRFLS_FK FOREIGN KEY ( ID_PERFIL ) REFERENCES T_PERFILES ( ID_PERFIL ) ;

ALTER TABLE T_PERFIL_NIVEL_APROB ADD CONSTRAINT T_PRF_NVL_APROB_T_NVL_APROB_FK FOREIGN KEY ( ID_NIVEL_APROB ) REFERENCES T_NIVEL_APROB ( ID_NIVEL ) ;

ALTER TABLE T_PRESUP_TIPO ADD CONSTRAINT T_PRSUP_TIPO_T_PRESUP_FK FOREIGN KEY ( ID_PRESUPUESTO ) REFERENCES T_PRESUP ( ID_PRESUPUESTO ) ;

ALTER TABLE T_PRESUP_TIPO ADD CONSTRAINT T_PRSUP_TIPO_T_TIPPRE_FK FOREIGN KEY ( ID_TIPO ) REFERENCES T_TIPO_PRESUP ( ID_TIPO_PRESUP ) ;

ALTER TABLE T_VERSION ADD CONSTRAINT T_VERSION_T_PRESUP_TIPO_FK FOREIGN KEY ( ID_PRESUPUESTO_TIPO ) REFERENCES T_PRESUP_TIPO ( ID_PRESUPUESTO_TIPO ) ;


-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            17
-- CREATE INDEX                             0
-- ALTER TABLE                             32
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
