CREATE SEQUENCE T_ARCHIVO_AI START WITH 1;

CREATE OR REPLACE TRIGGER T_ARCHIVO_AI_TRIG
BEFORE INSERT ON T_ARCHIVO
FOR EACH ROW
BEGIN
    
    SELECT T_ARCHIVO_AI.NEXTVAL
    INTO :new.ID_ARCHIVO
    FROM dual;

END;