CREATE SEQUENCE T_DET_VERSION_AI START WITH 1;

CREATE OR REPLACE TRIGGER T_DET_VERSION_AI_TRIG
BEFORE INSERT ON T_DET_VERSION
FOR EACH ROW
BEGIN
    
    SELECT T_DET_VERSION_AI.NEXTVAL
    INTO :new.ID_DETALLE
    FROM dual;

END;