CREATE SEQUENCE T_MES_ENT_SOL_AI START WITH 1;

CREATE OR REPLACE TRIGGER T_MES_ENT_SOL_AI_TRIG
BEFORE INSERT ON T_MES_ENT_SOL
FOR EACH ROW
BEGIN
    
    SELECT T_MES_ENT_SOL_AI.NEXTVAL
    INTO :new.ID_MES_ENTREGA
    FROM dual;

END;