CREATE SEQUENCE T_OBSERVACIONES_AI START WITH 1;

CREATE OR REPLACE TRIGGER T_OBSERVACIONES_AI_TRIG
BEFORE INSERT ON T_OBSERVACIONES
FOR EACH ROW
BEGIN
    
    SELECT T_OBSERVACIONES_AI.NEXTVAL
    INTO :new.ID_OBSERVACIONES
    FROM dual;

END;