CREATE SEQUENCE T_PRIORIDAD_AI START WITH 1;

CREATE OR REPLACE TRIGGER T_PRIORIDAD_AI_TRIG
BEFORE INSERT ON T_PRIORIDAD
FOR EACH ROW
BEGIN
    
    SELECT T_PRIORIDAD_AI.NEXTVAL
    INTO :new.ID_PRIORIDAD
    FROM dual;

END;