CREATE SEQUENCE T_PRESUP_TIPO_AI START WITH 1;

CREATE OR REPLACE TRIGGER T_PRESUP_TIPO_AI_TRIG
BEFORE INSERT ON T_PRESUP_TIPO
FOR EACH ROW
BEGIN
    SELECT T_PRESUP_TIPO_AI.NEXTVAL
    INTO :new.ID_PRESUPUESTO_TIPO
    FROM dual;
END;