CREATE SEQUENCE T_TIPO_PRESUP_AI START WITH 1;

CREATE OR REPLACE TRIGGER T_TIPO_PRESUP_AI_TRIG
BEFORE INSERT ON T_TIPO_PRESUP
FOR EACH ROW
BEGIN
    
    SELECT T_TIPO_PRESUP_AI.NEXTVAL
    INTO :new.ID_TIPO_PRESUP
    FROM dual;

END;