CREATE SEQUENCE T_VERSION_AI START WITH 1;

CREATE OR REPLACE TRIGGER T_VERSION_AI_TRIG
BEFORE INSERT ON T_VERSION
FOR EACH ROW
BEGIN
    
    SELECT T_VERSION_AI.NEXTVAL
    INTO :new.ID_VERSION
    FROM dual;

END;